package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 13 15:49:56 BST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for PaProjectsAllView1.
     * @return PaProjectsAllView1
     */
    public ViewObjectImpl getPaProjectsAllView1() {
        return (ViewObjectImpl)findViewObject("PaProjectsAllView1");
    }
}
